### ISSUE TITLE
"ISSUEベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kawasakiairi** [kawasakiairi/portfolio#40]
### 概要

激辛食品専門のレビューサイトをRuby on Railsで開発する。
ユーザーが食品を検索し、食品に対してレビューを投稿・閲覧できる機能を提供する。
お気に入り機能やSNSシェア機能も実装する。

### 実装予定の機能

- [ ]  マルチ検索
- [ ]  検索結果一覧 閲覧
- [ ]  食品詳細 閲覧
- [ ]  レビュー一覧 閲覧
- [ ]  レビュー詳細 閲覧
- [ ]  レビュー 投稿 / 編集 / 削除
- [ ]  マイページ 閲覧 / 編集
- [ ]  ログイン / ログアウト
- [ ]  ユーザー 登録 / 削除
- [ ]  メールアドレス 変更
- [ ]  パスワード 変更
- [ ]  お気に入り食品 登録 / 解除
- [ ]  お気に入りレビュー 登録 / 解除
- [ ]  レビュー投稿のX（旧Twitter）シェア

### 必要なページ

- [ ]  トップページ
- [ ]  検索結果一覧ページ
- [ ]  食品詳細ページ（レビュー一覧含む）
- [ ]  レビュー詳細ページ
- [ ]  レビュー投稿ページ
- [ ]  レビュー編集ページ
- [ ]  マイページ（お気に入り食品タグ）
- [ ]  マイページ（お気に入りレビュータグ）
- [ ]  マイページ編集ページ
- [ ]  ログインページ
- [ ]  ユーザー登録ページ
- [ ]  ログイン情報変更ページ
- [ ]  アプリ概要ページ
- [ ]  利用規約ページ
- [ ]  プライバシーポリシーのページ
- [ ]  お問い合わせページ

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。概ね良いかと思います。LGTMです。

---

ストーリーポイント4のものは3以下になるように細かくissue立てしましょう。

以下、MVPに含めなくても良いと思ったカードになります。
- 利用規約
- プライバシーポリシー
- お問い合わせ
- お気に入り
- マイページ
- 会員情報削除
- ログイン情報変更
- パスワード変更
- メールアドレス変更
- SNS
- RSpec

**Comment by kawasakiairi** [comment]
レビューありがとうございます。
MVPリリースに含めない項目はif Possible項目を作成し、以降しました。
